try : 
    print(num)
except : 
    print ("Exception: ")